services:
  app:
    container_name: app
    hostname: app
    build:
      context: ./app
      dockerfile: Dockerfile
    command: uv run gunicorn neuropost.wsgi:application --workers 2 --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - ./app/.env
    depends_on:
      - postgres

  bot:
    container_name: bot
    hostname: bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    command: uv run src/bot.py
    ports:
      - "8001:8001"
    env_file:
      - ./bot/.env
    depends_on:
      - postgres

  celery-worker:
    container_name: celery-worker
    hostname: celery-worker
    build:
      context: ./app
      dockerfile: Dockerfile_celery
    command: uv run celery -A neuropost worker --loglevel=info
    env_file:
      - ./app/.env
    depends_on:
      - redis
      - postgres

  postgres:
    container_name: postgres
    hostname: postgres
    image: "postgres:17.5"
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_volume:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:8.0.3-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_volume:/data
    env_file:
      - .env

volumes:
  postgres_volume:
  redis_volume:
