
services:
  web:
    build: .
    command: python -m gunicorn --bind 0.0.0.0:5001 web_app:app
    ports:
      - "5001:5001"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    restart: always

volumes:
  postgres_data:
